export const blogTabs = [
  "all",
  "annoucement",
  "best practics",
  "career growth",
  "contingent search",
  "finding a job",
  "interview tips",
  "retained search",
  "startup",
  "technology staffing",
  "technology trends",
  "trends",
  "uncategorized",
];
